#!/usr/bin/env bash
# Regenerate the per-tool adapters in dist/ from the canonical sources in src/.
# Edit src/, run ./build.sh, commit both.
set -euo pipefail
cd "$(dirname "$0")"

ALWAYS_ON=src/always-on.md
LOOP=src/teaching-loop.md

mkdir -p dist/claude/.claude/skills/study-companion \
         dist/cursor/.cursor/rules \
         dist/codex/.study-companion

# ---------------------------------------------------------------- Claude Code
# Always-on half goes in CLAUDE.md (loaded into every context).
# Deep half goes in a skill (loaded by the model when the description matches).
{
  echo "<!-- generated by build.sh from src/always-on.md - do not edit here -->"
  echo
  cat "$ALWAYS_ON"
  echo
  echo "When the student is working on understanding a concept, use the"
  echo "\`study-companion\` skill for the full teaching loop."
} > dist/claude/CLAUDE.md

{
  echo "---"
  cat src/skill-frontmatter.yaml
  echo "---"
  echo
  cat "$LOOP"
  echo
  echo "---"
  echo
  echo "## Default posture (also active outside this skill)"
  echo
  sed '1,2d' "$ALWAYS_ON"
} > dist/claude/.claude/skills/study-companion/SKILL.md

cp templates/profile.md dist/claude/.claude/skills/study-companion/profile-template.md

# --------------------------------------------------------------------- Cursor
{
  echo "---"
  echo "description: Study companion - default teaching posture"
  echo "alwaysApply: true"
  echo "---"
  echo
  cat "$ALWAYS_ON"
} > dist/cursor/.cursor/rules/study-companion.mdc

{
  echo "---"
  echo "description: Full teaching loop - diagnose, attempt, explain, self-explain, test, map. Fetch when the student is trying to understand a concept, is stuck on a course exercise, or asks to be quizzed."
  echo "alwaysApply: false"
  echo "---"
  echo
  cat "$LOOP"
} > dist/cursor/.cursor/rules/study-companion-loop.mdc

# ---------------------------------------------------------------------- Codex
{
  echo "<!-- generated by build.sh - do not edit here -->"
  echo
  cat "$ALWAYS_ON"
  echo
  echo "## Going deeper"
  echo
  echo "When the student is working on understanding a concept rather than"
  echo "executing a task, read \`.study-companion/teaching-loop.md\` and follow it."
} > dist/codex/AGENTS.md

cp "$LOOP" dist/codex/.study-companion/teaching-loop.md
cp templates/profile.md dist/codex/.study-companion/profile-template.md

echo "built:"
find dist -type f | sort | sed 's/^/  /'
