#!/usr/bin/env bash
# Regenerate the per-tool adapters in dist/ from the canonical sources in src/.
# Edit src/, run ./build.sh, commit both.
set -euo pipefail
cd "$(dirname "$0")"

ALWAYS_ON=src/always-on.md
LOOP=src/teaching-loop.md

mkdir -p dist/claude/.claude/skills/study-companion \
         dist/cursor/.cursor/rules \
         dist/codex/.study-companion

# ---------------------------------------------------------------- Claude Code
# Always-on half goes in CLAUDE.md (loaded into every context).
# Deep half goes in a skill (loaded by the model when the description matches).
{
  echo "<!-- generated by build.sh from src/always-on.md - do not edit here -->"
  echo
  cat "$ALWAYS_ON"
  echo
  echo "When the student is working on understanding a concept, use the"
  echo "\`study-companion\` skill for the full teaching loop."
} > dist/claude/CLAUDE.md

{
  echo "---"
  cat src/skill-frontmatter.yaml
  echo "---"
  echo
  cat "$LOOP"
  echo
  echo "---"
  echo
  echo "## Default posture (also active outside this skill)"
  echo
  sed '1,2d' "$ALWAYS_ON"
} > dist/claude/.claude/skills/study-companion/SKILL.md

cp templates/profile.md dist/claude/.claude/skills/study-companion/profile-template.md

# --------------------------------------------------------------------- Cursor
{
  echo "---"
  echo "description: Study companion - default teaching posture"
  echo "alwaysApply: true"
  echo "---"
  echo
  cat "$ALWAYS_ON"
} > dist/cursor/.cursor/rules/study-companion.mdc

# The deep half ships as a Cursor Agent Skill. Same SKILL.md contract as Claude
# Code (name + description; folder name must equal name), and Cursor discovers
# skills from ~/.cursor/skills/ globally as well as .cursor/skills/ per project.
mkdir -p dist/cursor/skills/study-companion
cp dist/claude/.claude/skills/study-companion/SKILL.md \
   dist/cursor/skills/study-companion/SKILL.md
cp templates/profile.md dist/cursor/skills/study-companion/profile-template.md

# Cursor "User Rules" (Settings > Rules) are global across every project but are
# plain text pasted into the UI - no file, no frontmatter. Emit a paste-ready copy.
{
  cat "$ALWAYS_ON"
} > dist/cursor/user-rules.txt

# ---------------------------------------------------------------------- Codex
{
  echo "<!-- generated by build.sh - do not edit here -->"
  echo
  cat "$ALWAYS_ON"
  echo
  echo "## Going deeper"
  echo
  echo "When the student is working on understanding a concept rather than"
  echo "executing a task, read \`.study-companion/teaching-loop.md\` and follow it."
} > dist/codex/AGENTS.md

cp "$LOOP" dist/codex/.study-companion/teaching-loop.md
cp templates/profile.md dist/codex/.study-companion/profile-template.md

# -------------------------------------------------------------------- VS Code
# One bundle for a course folder. scripts/export-vscode-bundle.sh copies it into
# the folder's root AND its project/ folder, so the tutor works in whichever one
# a student opens. Covers GitHub Copilot and assistants that read AGENTS.md.
#
# Students run this on the free Copilot model, which cannot follow the long
# teaching loop: it keeps the easy rules and drops the ones that teach. So this
# bundle carries only the short, unconditional rules in src/vscode/tutor.md.
TUTOR=src/vscode/tutor.md
V=dist/vscode
rm -rf "$V"
mkdir -p "$V/.github/agents" "$V/.vscode"

{
  echo "<!-- generated by build.sh from src/vscode/tutor.md - do not edit here -->"
  echo
  cat "$TUTOR"
} > "$V/.github/copilot-instructions.md"

{
  echo "---"
  echo "name: Tutor"
  echo "description: Coaches you towards the answer instead of writing it. Reads your files, never edits them."
  echo "tools: ['read', 'search', 'vscode/askQuestions']"
  echo "---"
  echo
  cat "$TUTOR"
} > "$V/.github/agents/tutor.agent.md"

{
  echo "<!-- generated by build.sh from src/vscode/tutor.md - do not edit here -->"
  echo
  cat "$TUTOR"
} > "$V/AGENTS.md"

cp src/vscode/extensions.json "$V/.vscode/extensions.json"

cat > "$V/.vscode/settings.json" <<'SETTINGS'
// Course tutoring setup - generated by learning-skills/build.sh.
// Changing these settings switches parts of the AI tutor off.
{
  // Copilot: don't write code as the student types, in Python files or notebooks.
  "github.copilot.enable": {
    "*": true,
    "plaintext": false,
    "markdown": false,
    "scminput": false,
    "python": false,
    "jupyter": false
  },
  "github.copilot.nextEditSuggestions.enabled": false,

  // Copilot already gets the rules from .github/copilot-instructions.md.
  // AGENTS.md carries the same rules for other assistants; don't load them twice.
  "chat.useAgentsMdFile": false
}
SETTINGS

echo "built:"
find dist -type f | sort | sed 's/^/  /'
